pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "wdk-starter-kotlin"
include ':app'
include ':wdk-core-kotlin'
project(':wdk-core-kotlin').projectDir = new File(settingsDir, '../wdk-core-kotlin')
